[colors.bright]
black = "#879089"
blue = "#498693"
cyan = "#4a7074"
green = "#dfb064"
magenta = "#5e9577"
red = "#934b4b"
white = "#c1cfc5"
yellow = "#998f6c"

[colors.normal]
black = "#0e0f0e"
blue = "#71abb7"
cyan = "#527d81"
green = "#dfb064"
magenta = "#5e9577"
red = "#d75f5f"
white = "#c1cfc5"
yellow = "#ffe2a9"

[colors.primary]
background = "#0e0f0e"
foreground = "#bbd0d3"

[cursor]
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
opacity = 0.88

[window.dimensions]
columns = 85
lines = 30

[window.padding]
x = 7
y = 7

[window.position]
x = 1300
y = 0
